# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82ce606d92a4aedb466e6744055cebb165d0c1ddaa9fe4cbd60769e0b412a1e7c45eb564962e52e5294e7ac615557e60b2f46d534130947c812dd628e48ddaba

test:
  secret_key_base: 04ba3d7778539ab0937e696fcb72b9645df22e2714c2387431d4f99c6dbb9f36c3be70ba65f573bd04410e4237e30cde8c55fbc4d9e4c516d44eec802e28209e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
